#+title: Minecraft Modding on 1.8.9: Setting up Java
#+author: Cam A.
#+date: 2026-04-29

#+html_head: <link rel="stylesheet" href="../styles.css">


* Getting Started
So you want to program a Minecraft mod for 1.8.9.
It's a niche genre of person who wants to do that, I can respect it.
If you only came here for source code examples, they can be found on my Github here (fix me before posting).

The first thing you're going to need is a JDK, or Java Development Toolkit, and for 1.8.9, you'll need Java 8 specifically.
I personally use OpenJDK, which can be downloaded [[https://github.com/adoptium/temurin8-binaries/releases/tag/jdk8u482-b08][here]], and you'll want the version starting with ~OpenJDK8U-jdk_<your-cpu-arch>_<your-OS>~.
For example, if you're on windows, with a 64 bit x64 CPU, then you download ~OpenJDK8U-jdk_x64_windows_hotspot_8u482b08.msi~ (if you don't know which is you, it's probably this one).
After getting that, you'll also need the 1.8.9 [[https://files.minecraftforge.net/net/minecraftforge/forge/index_1.8.9.html][MDK]] (Minecraft Development Toolkit), [[https://git-scm.com/install//windows][git]], and [[https://eclipseide.org/][Eclipse IDE]] (you can use whatever IDE you want, but this guide will be in Eclipse, because they gave me a pen at FOSDEM).
And if you don't already have a Github account, now would probably be the time to make one (much like the editor, it doesn't have to be Github, but I'll be focusing on it).

After going through the Java installer, go into powershell, and go to wherever you downloaded the MDK zip to.
You can either do this by opening the folder in File Explorer, right clicking, and clicking open in terminal, or by using the ~cd~ command, which would look something like this (~cd~ stands for "change directory"; directory is just another name for folder).
#+begin_src shell
  cd '\.Downloads\'
#+end_src

Then, create a new directory called ~minecraft-forge-1.8.9~, move the MDK zip file into it, and then unzip it.
Again, you can do this with the File Explorer, or with a command.
#+begin_src shell
  unzip forge-1.8.9-11.15.1.2318-1.8.9-mdk.zip
#+end_src

Now, simply run ~.\gradlew.bat runClient~, and modded Minecraft will start (note that it might take a while trying to download things).
Granted, there are barely any running in it, but we'll fix that soon enough.

* What's That Gradlew.bat thing?
~gradlew.bat~ is a little program that controls something called [[https://gradle.org/][Gradle]].
Gradle is a build system, which is a piece of software that helps us compile and run code.
Some projects have thousands of files, and it would be a pain to compile each of those by hand, so these programs do it for us.

* Setting up Eclipse
Open eclipse, and select wherever it is that you extracted the forge zip to as the project root.
To ensure we're using the correct version of Java (OpenJDK 8), go to Window, then select Preferences.
From there, go select Java, then Installed JREs (Java Runtime Environments), and select Java 8.
If Java 8 isn't there, then something has gone wrong, and you should fix that before going any further.

* A Taste of Java 8
Create a new folder, and put two Java files into it -- ~Main.java~, and ~Student.java~, and then write the following into them.
For ~Student.java~, write
#+begin_src java
  /**
   ,* A basic call for describing a student at a school.
   ,*
   ,* @author Cam A.
   ,* @version 1.0
   ,*/
  public class Student {
      private String firstName;
      private String lastName;
      private int age;

      /**
       ,* Constructs a new Student object.
       ,*
       ,* @param firstName the first name of the student
       ,* @param lastName the last name of the student
       ,* @param age the age of the student
       ,*/
      public Student(String firstName, String lastName, int age) {
  	this.firstName = firstName;
  	this.lastName = lastName;
  	this.age = age;
      }

      /**
       ,* Getter function for the students name. Combines the firstName
       ,* and lastName private variables.
       ,*
       ,* @return the full name of the student
       ,*/
      public String getName() {
  	return(this.firstName + " " + this.lastName);
      }

      /**
       ,* Getter function for the students age, int years.
       ,*
       ,* @return the age of the student
       ,*/
      public int getAge() {
  	return(this.age);
      }

      /**
       ,* Increases the students age in years.
       ,*
       ,* @param howManyYearsOlder how many years older the student now is
       ,*/
      public void gottenOlder(int howManyYearsOlder) {
  	this.age = this.age + howManyYearsOlder;
      }

      /**
       ,* Checks if the student is 18 yet.
       ,*
       ,* @return true if the student is older than 18, and false otherwise
       ,*/
      public boolean isStudentEighteen() {
  	if(this.age < 18) {
  	    return(false);
  	} else {
  	    return(true);
  	}
      }
  }
#+end_src

And for ~Main.java~, write
#+begin_src java
  /**
   ,* Main class.
   ,*
   ,* @author Cam A.
   ,* @version 1.0
   ,*/
  public class Main {
      /**
       ,* Adds a new student. Warning: will crash if less than three arguments
       ,* are provided.
       ,*
       ,* @param args the students first name, followed by their last name, followed by their age
       ,* @see Student
       ,*/
      public static void main(String[] args) {
  	Student newStudent = new Student(args[0],
  				 args[1],
  				 Integer.parseInt(args[2]));

  	System.out.println("Student " + newStudent.getName() + " is " + newStudent.getAge() + " years old.");
      }
  }
#+end_src

Now, you can run ~javac Main.java Student.java~, and then ~java Main Gerard Way 49~ (yes I was listening to MCR while writing this, how could you tell?) in the Eclipse terminal (after opening this as a project, of course).
What happens if you don't include any arguments to ~Main~?

* Exercises
1. Make it so the program doesn't crash when you don't give it good arguments.
   This is sometimes known as defensive programming.
2. Add your own JavaDoc (the special comments) for the things you've edited, and give yourself credit with an ~@author~ tag.
3. Add a new feature to ~Student.java~, that changes the student's name.
   After this, try changing ~Main.java~ so that the fourth argument is the new name of the student.
